// Generated by gencpp from file inexbot_reva_service/Person.msg
// DO NOT EDIT!


#ifndef INEXBOT_REVA_SERVICE_MESSAGE_PERSON_H
#define INEXBOT_REVA_SERVICE_MESSAGE_PERSON_H

#include <ros/service_traits.h>


#include <inexbot_reva_service/PersonRequest.h>
#include <inexbot_reva_service/PersonResponse.h>


namespace inexbot_reva_service
{

struct Person
{

typedef PersonRequest Request;
typedef PersonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Person
} // namespace inexbot_reva_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inexbot_reva_service::Person > {
  static const char* value()
  {
    return "c198113e7dd9cc5c9fd5f271c8479b39";
  }

  static const char* value(const ::inexbot_reva_service::Person&) { return value(); }
};

template<>
struct DataType< ::inexbot_reva_service::Person > {
  static const char* value()
  {
    return "inexbot_reva_service/Person";
  }

  static const char* value(const ::inexbot_reva_service::Person&) { return value(); }
};


// service_traits::MD5Sum< ::inexbot_reva_service::PersonRequest> should match
// service_traits::MD5Sum< ::inexbot_reva_service::Person >
template<>
struct MD5Sum< ::inexbot_reva_service::PersonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inexbot_reva_service::Person >::value();
  }
  static const char* value(const ::inexbot_reva_service::PersonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inexbot_reva_service::PersonRequest> should match
// service_traits::DataType< ::inexbot_reva_service::Person >
template<>
struct DataType< ::inexbot_reva_service::PersonRequest>
{
  static const char* value()
  {
    return DataType< ::inexbot_reva_service::Person >::value();
  }
  static const char* value(const ::inexbot_reva_service::PersonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inexbot_reva_service::PersonResponse> should match
// service_traits::MD5Sum< ::inexbot_reva_service::Person >
template<>
struct MD5Sum< ::inexbot_reva_service::PersonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inexbot_reva_service::Person >::value();
  }
  static const char* value(const ::inexbot_reva_service::PersonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inexbot_reva_service::PersonResponse> should match
// service_traits::DataType< ::inexbot_reva_service::Person >
template<>
struct DataType< ::inexbot_reva_service::PersonResponse>
{
  static const char* value()
  {
    return DataType< ::inexbot_reva_service::Person >::value();
  }
  static const char* value(const ::inexbot_reva_service::PersonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INEXBOT_REVA_SERVICE_MESSAGE_PERSON_H
